---
# ZABBIX PROXY INSTALLER
- hosts: all
  tasks:
      - name: Create Temporary Folder for downloads.
        become: yes
        file: state=directory path=/tmp/zabbix/
        
      - name: Download ZABBIX Repository.
        become: yes
        get_url: url=https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb dest=/tmp/zabbix/
        
      - name: Install ZABBIX Repository.
        become: yes
        apt: deb=/tmp/zabbix/zabbix-release_6.0-4+ubuntu22.04_all.deb
        
      - name: Execute apt update.
        become: yes
        apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
        
      - name: Install ZABBIX Proxy
        become: yes
        apt: name=zabbix-agent
        
      - name: Restart Zabbix Agent
        become: yes
        systemd: name=zabbix-agent state=restarted

      - name: Enable Zabbix Agent on Startup.
        become: yes
        systemd: name=zabbix-agent enable